[package]
name = "RedditNobility"
version = "0.1.0"
authors = ["Wyatt Jacob Herkamp <wherkamp@kingtux.me>"]
edition = "2018"

[dependencies]

diesel = { version = "1.4.7", features = ["mysql", "r2d2"] }
diesel_migrations = "1.4.0"
r2d2 = "0.8.9"
r2d2_mysql = "*"
dotenv = "0.15.0"
actix = "0.10"

serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
serde_qs = "0.8.3"
zip = "0.5.13"
futures = "0.3.15"
sanitize-filename = "0.3"
actix-files = "0.5.0"
env_logger = "0.8"
tera = "1.15.0"
new-rawr = { git = "https://github.com/wherkamp/new-rawr.git" }
bcrypt = "0.10.0"
rand = "0.8.4"
futures-util = "0.3.15"
actix-web = { version = "3.3.2", features = ["openssl"] }
openssl = { version = "0.10", features = ["v110"] }
log4rs = "1.0.0"
log = "0.4.14"
strum = { version = "0.21.0", features = ["derive"] }
strum_macros = "0.21.1"
derive_more = "0.99.14"
chrono = "0.4.19"
hyper = "0.13.9"
hyper-tls = "0.4.3"
time = "0.2.27"
actix-multipart = "0.3"
