[package]
name = "RedditRoyalty"
version = "0.1.0"
authors = ["Wyatt Jacob Herkamp <wherkamp@kingtux.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

diesel = { version = "1.4.6", features = ["mysql","r2d2"] }
diesel_migrations =  "1.4.0"
r2d2 = "0.8.9"
r2d2_mysql="*"
dotenv = "0.15.0"
actix = "0.10"
actix-web = "3"
actix-web-actors = "3"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0.64"
zip = "0.5.11"
futures = "0.3.1"
sanitize-filename = "0.3"
actix-files = "0.5.0"
env_logger = "0.8"
tera = "1.7.0"
actix-session = "0.4.1"
new-rawr= {git="https://github.com/wherkamp/new-rawr.git"}
bcrypt = "0.9.0"
rand = "0.8.3"