name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        working-directory: site
        node-version: 16.x
    - name: Install Site
      working-directory: site
      run: npm install
    - name: Build Site
      working-directory: site
      run: npm run build
      env: 
        API_URL: https://nitro.repo.kingtux.me:8989
