name: Pull Request Rust

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'rust')    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Update Rust
        run: rustup update
      - name: Test
        run: cargo test
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

